cbas.cbas_external_links_CB_cluster.CBASExternalLinks:
    test_create_external_link,GROUP=x509
    test_create_external_link,dataverse=3,link=5,GROUP=x509

    test_list_external_links,GROUP=basic_functionality
    test_list_external_links, encryption=full,GROUP=x509

    test_alter_link_properties,GROUP=rebalance

    test_connect_link,GROUP=basic_functionality
    test_disconnect_link,GROUP=basic_functionality
    test_create_dataset,GROUP=basic_functionality
    test_query_dataset,GROUP=basic_functionality

    test_effect_of_rbac_role_change_on_external_link,GROUP=user_role_changes

    test_data_ingestion_after_reducing_and_then_restoring_remote_user_permission,GROUP=user_role_changes
    test_data_ingestion_after_reducing_and_then_restoring_remote_user_permission,after_timeout=True,GROUP=user_role_changes

    test_data_ingestion_after_daleting_and_then_recreating_remote_user,has_bucket_access=True,same_role=False,GROUP=user_role_changes
    test_data_ingestion_after_daleting_and_then_recreating_remote_user,has_bucket_access=True,same_role=True,GROUP=user_role_changes
    test_data_ingestion_after_daleting_and_then_recreating_remote_user,has_bucket_access=False,validate_error_msg=True,error_msg=Connect link failed,GROUP=user_role_changes
    test_data_ingestion_after_daleting_and_then_recreating_remote_user,has_bucket_access=True,same_role=False,after_timeout=True,GROUP=user_role_changes
    test_data_ingestion_after_daleting_and_then_recreating_remote_user,has_bucket_access=True,same_role=True,after_timeout=True,GROUP=user_role_changes
    test_data_ingestion_after_daleting_and_then_recreating_remote_user,has_bucket_access=False,after_timeout=True,validate_error_msg=True,error_msg=Connect link failed,GROUP=user_role_changes

    test_dataset_creation_when_network_down,validate_error=True,expected_error=Cannot connect to host,GROUP=network
    test_dataset_creation_when_network_down,network_up_before_timeout=True,GROUP=network
    
    test_connect_link_when_network_up_before_timeout,GROUP=network
    test_data_ingestion_resumes_when_network_up_before_timeout,GROUP=network
    test_reconnecting_link_after_timeout_due_to_network_failure,GROUP=network
    
    test_dataset_behaviour_on_remote_bucket_deletion,GROUP=remote_data_modification
    # Removing below test case, as force flag during link creation has been deprecated and is ignored by CBAS, 
    #so both the test cases essentially do the same thing.
    #test_dataset_behaviour_on_remote_bucket_deletion_and_recreation,GROUP=remote_data_modification
    test_dataset_behaviour_on_remote_bucket_deletion_and_recreation,with_force_flag=True,GROUP=remote_data_modification
    
    test_data_ingestion_for_data_updation_in_remote_cluster,GROUP=remote_data_modification
    test_data_ingestion_for_data_deletion_in_remote_cluster,GROUP=remote_data_modification
    
    test_analytics_cluster_while_remote_cluster_swap_rebalancing,run_query=False,,GROUP=rebalance
    test_analytics_cluster_while_remote_cluster_swap_rebalancing,run_query=True,num_queries=10,GROUP=rebalance
    
    test_analytics_cluster_swap_rebalancing,run_query=True,num_queries=10,GROUP=rebalance
    test_analytics_cluster_swap_rebalancing,run_query=False,GROUP=rebalance
    
    test_analytics_cluster_when_rebalancing_in_cbas_node,run_query=True,num_queries=10,GROUP=rebalance
    test_analytics_cluster_when_rebalancing_in_cbas_node,run_query=False,GROUP=rebalance
    
    test_analytics_cluster_when_rebalancing_out_cbas_node,run_query=True,num_queries=10,GROUP=rebalance
    test_analytics_cluster_when_rebalancing_out_cbas_node,run_query=False,GROUP=rebalance
    
    test_fail_over_cbas_node_followed_by_rebalance_out_or_add_back,run_query=False,rebalance_out=False,GROUP=rebalance
    test_fail_over_cbas_node_followed_by_rebalance_out_or_add_back,run_query=False,rebalance_out=True,GROUP=rebalance
    test_fail_over_cbas_node_followed_by_rebalance_out_or_add_back,run_query=True,rebalance_out=False,recovery_strategy=full,GROUP=rebalance
